apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: "true"
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${NAME}
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${SIZE}
    volumeName: pv0040
  status: {}
