---
openshift_cluster_content:
- object: projectrequest
  content:
  - name: ci-cd
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
    params: "{{ inventory_dir }}/params/projectrequests/ci-cd"
    template_action: create
    tags:
    - projects
  - name: dev
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
    params: "{{ inventory_dir }}/params/projectrequests/dev"
    template_action: create
    tags:
    - projects
  - name: demo
    template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
    params: "{{ inventory_dir }}/params/projectrequests/demo"
    template_action: create
    tags:
    - projects
- object: ci-cd-builds
  content:
  - name: jenkins-s2i
    template: "https://raw.githubusercontent.com/rht-labs/labs-ci-cd/v0.3.0/openshift-templates/jenkins-s2i-build/template.json"
    params: "{{ inventory_dir }}/params/build/jenkins_s2i"
    namespace: labs-ci-cd
    tags:
    - jenkins
  - name: mvn-jenkins-slave
    template: "https://raw.githubusercontent.com/rht-labs/labs-ci-cd/v0.3.0/openshift-templates/jenkins-slave-pod/template.json"
    params: "{{ inventory_dir }}/params/build/maven_build_pod"
    namespace: labs-ci-cd
    tags:
    - jenkins-slaves
  - name: zap-jenkins-slave
    template: "https://raw.githubusercontent.com/rht-labs/labs-ci-cd/v0.3.0/openshift-templates/jenkins-slave-pod/template.json"
    params: "{{ inventory_dir }}/params/build/zap_build_pod"
    namespace: labs-ci-cd
    tags:
    - jenkins-slaves
- object: ci-cd-deployments
  content:
  - name: jenkins-ephemeral
    template: "{{ inventory_dir }}/templates/jenkins-ephemeral.yaml"
    params: "{{ inventory_dir }}/params/deploy/jenkins"
    namespace: labs-ci-cd
    tags:
    - jenkins
  - name: nexus
    template: "https://raw.githubusercontent.com/rht-labs/labs-ci-cd/v0.3.0/openshift-templates/nexus/template.json"
    params: "{{ inventory_dir }}/params/deploy/nexus"
    namespace: labs-ci-cd
    tags:
    - nexus
  - name: sonarqube-postgresql
    template: "openshift//postgresql-persistent"
    params: "{{ inventory_dir }}/params/deploy/postgresql"
    namespace: labs-ci-cd
    tags:
    - sonar
  - name: sonarqube
    template: "https://raw.githubusercontent.com/rht-labs/labs-ci-cd/v0.3.0/openshift-templates/sonarqube/template.json"
    params: "{{ inventory_dir }}/params/build-and-deploy/sonarqube"
    namespace: labs-ci-cd
    tags:
    - sonar
- object: app-builds
  content:
  - name: demo-labs-spring-build
    template: "https://raw.githubusercontent.com/rht-labs/labs-ci-cd/v0.3.0/openshift-templates/s2i-app-build/template-no-secrets.json"
    params: "{{ inventory_dir }}/params/build/demo-labs-spring"
    namespace: labs-ci-cd
- object: app-deploy
  content:
  - name: demo-labs-spring-dev
    template: "{{ inventory_dir }}/templates/demo-labs-spring-dev.json"
    params: "{{ inventory_dir }}/params/deploy/demo-labs-spring-dev"
    namespace: labs-dev
    tags:
    - demo-labs-spring
  - name: demo-labs-spring-demo
    template: "{{ inventory_dir }}/templates/demo-labs-spring-dev.json"
    params: "{{ inventory_dir }}/params/deploy/demo-labs-spring-demo"
    namespace: labs-demo
    tags:
    - demo-labs-spring